### ISSUE TITLE
Add requirements.txt

### ISSUE THREAD

**Issue by satreix** [tdhunt631/JobBoard#1]
I tried to install your app to give it a shot. So far I installed the following using python3:

```
Django==1.8.6
django-endless-pagination==2.0
django-registration==1.0
django-summernote==0.6.16
sorl-thumbnail==12.3
```

Doing a `manage.py syncdb` I get the following error:

```
File "VENV/lib/python3.5/site-packages/django/forms/models.py", line 274, in __new__
    "needs updating." % name
django.core.exceptions.ImproperlyConfigured: Creating a ModelForm without either the 'fields' attribute or the 'exclude' attribute is prohibited; form SubscribeForm needs updating.
```

I cannot get you application to work yet.
Can you please add a _requirements.txt_ to your repository.

**Comment by tdhunt631** [comment]
This was developed using Python 2.7 and Django 1.5.  It may be a compatibility issue.
